Circleci project setup
GabRayz/Phoenix-Bot pull request #49
Opened 2022-07-03 09:51 UTC by ViriMo

# CircleCi environ FINI mais
- @GabRayz créer un compte sur dockerhub pour pouvoir push l'image sur ton compte (et eventuellement changer le config.yml de circleCI avec tes ids et pwd (qu'il faudra mettre en env var pour pas l'afficher et utiliser password-stdin))
- Voir la stratégie de push de l'image (build de l'image a chaque push ? parait overkill. Build de l'image a chaque merge master ? Build de l'image a la main ?)

2022-07-03 10:02 UTC, ViriMo commented
@GabRayz pour sonar  To use this orb, an organization admin must opt-in to using third party orbs in Organization Security settings.

2022-07-03 18:20 UTC, GabRayz commented
> * crée un compte sur dockerhub pour pouvoir push l'image sur ton compte (et eventuellement changer le config.yml de circleCI avec tes ids, pwd et le nom de l'image docker (qu'il faudra mettre en env var pour pas l'afficher et utiliser password-stdin))

J'ai ajouté un access token en variable d'environnement. Le nom de compte est `gabray`

> Voir la stratégie de push de l'image (build de l'image a chaque push ? parait overkill. Build de l'image a chaque merge master ? Build de l'image a la main ? faudra juste retirer la partie build et changer le nom de l'image docker dans ce cas )

La build à chaque fois. C'est là justement pour éviter de build à la main.

2022-07-04 07:58 UTC, GabRayz requested changes
- Destination de l'image à changer
- Le chemin vers le fichier de config doit être fourni au runtime, pas ajouté à l'image docker

2022-07-04 12:25 UTC, TonyHg approved these changes

2022-07-04 12:25 UTC, GabRayz approved these changes

2022-07-04 12:31 UTC, merged